# Generated by Django 4.2.1 on 2023-10-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transaction_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='available_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='account',
            name='payable_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
